<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="BenefitServiceExLITES" targetNamespace="http://wsdl/BenefitServiceExLITES_Interface_v1/BenefitServiceExLITES/v1" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:tns="http://wsdl/BenefitServiceExLITES_Interface_v1/BenefitServiceExLITES/v1" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:wsdl_1="http://anthem.com/service/BenefitServiceExLITES-Interface/v1"
	
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wspp="http://java.sun.com/xml/ns/wsit/policy" 
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsp="http://www.w3.org/ns/ws-policy" 
	xmlns:sc="http://schemas.sun.com/2006/03/wss/client" 
	xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" >
	
	<wsp1_2:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsu:Id="MyWebServicePortBindingPolicy">
      <wsp:ExactlyOne>
         <wsp1_2:All>
            <sp:AsymmetricBinding xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
               <wsp1_2:Policy>
                  <sp:InitiatorToken>
                     <wsp:Policy>
                        <sp:X509Token sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:InitiatorToken>
                  <sp:RecipientToken>
                     <wsp:Policy>
                        <sp:X509Token sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToInitiator">
                           <wsp1_2:Policy>
                              <sp:WssX509V3Token10 />
                           </wsp1_2:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:RecipientToken>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:TripleDesRsa15 />
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Strict />
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp />
                  <sp:OnlySignEntireHeadersAndBody />
               </wsp1_2:Policy>
            </sp:AsymmetricBinding>
            <sp:SignedParts xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
               <sp:Body />
            </sp:SignedParts>
            <sc:KeyStore wspp:visibility="private" callbackHandler="com.castlight.ws.healthfund.anthem.ws.callbacks.KeyStoreCallbackHandler" location="/Users/sreenivass/Projects/Ventana/servicelaunchpad/security/keystores/cacerts" storepass="changeit" alias="clh_prod" keypass="changeit" />
            <sc:TrustStore wspp:visibility="private" callbackHandler="com.castlight.ws.healthfund.anthem.ws.callbacks.TrustStoreCallbackHandler" storepass="changeit" peeralias="serverkey" />
         </wsp1_2:All>
      </wsp:ExactlyOne>
   </wsp1_2:Policy>
	
	<wsdl:import location="BenefitServiceExLITES_Interface_v1.wsdl" namespace="http://anthem.com/service/BenefitServiceExLITES-Interface/v1"/>
	<wsdl:binding name="BenefitServiceExLITESBinding" type="wsdl_1:BenefitServiceExLITES">
		<wsp1_2:PolicyReference URI="#MyWebServicePortBindingPolicy" />
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="GetAcctBalanceLITES">
			<soap:operation soapAction="GetAcctBalanceLITES"/>
			<wsdl:input>
				<soap:body parts="request" use="literal"/>
				<soap:header message="wsdl_1:GetAcctBalanceLITES_Request" part="header" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="response" use="literal"/>
				<soap:header message="wsdl_1:GetAcctBalanceLITES_Response" part="header" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="getAcctBalanceLITESFault">
				<soap:fault name="getAcctBalanceLITESFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="BenefitServiceExLITES">
		<wsdl:port binding="tns:BenefitServiceExLITESBinding" name="BenefitServiceExLITESPort">
			<soap:address location="https://prods-dp.WELLPOINT.COM/Member/1.0/BenefitServiceExLITES"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
